"""add users and portfolio ownership

Revision ID: 42410853c13e
Revises: 149957d84f0e
Create Date: 2026-08-15 16:54:59.626656

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42410853c13e"
down_revision: str | Sequence[str] | None = "149957d84f0e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.add_column("portfolios", sa.Column("user_id", sa.Integer(), nullable=True))
    connection = op.get_bind()

    portfolio_count = connection.execute(
        sa.text("SELECT COUNT(*) FROM portfolios")
    ).scalar_one()

    if portfolio_count > 0:
        legacy_user_id = connection.execute(
            sa.text(
                """
                INSERT INTO users (email, password_hash, full_name)
                VALUES (:email, :password_hash, :full_name)
                RETURNING id
                """
            ),
            {
                "email": "legacy-owner@internal.invalid",
                "password_hash": "!legacy-account-disabled",
                "full_name": "Legacy Owner",
            },
        ).scalar_one()

        connection.execute(
            sa.text(
                """
                UPDATE portfolios
                SET user_id = :legacy_user_id
                WHERE user_id IS NULL
                """
            ),
            {"legacy_user_id": legacy_user_id},
        )

    op.alter_column(
        "portfolios",
        "user_id",
        existing_type=sa.Integer(),
        nullable=False,
    )

    op.create_foreign_key(
        "fk_portfolios_user_id_users",
        "portfolios",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_index(
        "ix_portfolios_user_id_id",
        "portfolios",
        ["user_id", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_portfolios_user_id_id",
        table_name="portfolios",
    )
    op.drop_constraint(
        "fk_portfolios_user_id_users",
        "portfolios",
        type_="foreignkey",
    )
    op.drop_column("portfolios", "user_id")
    op.drop_table("users")
    # ### end Alembic commands ###
