"""create asset prices table

Revision ID: fedc53d5539c
Revises: 8507a81768b5
Create Date: 2026-07-27 17:34:33.699198

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fedc53d5539c"
down_revision: str | Sequence[str] | None = "8507a81768b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "portfolios",
        sa.Column(
            "base_currency", sa.String(length=3), server_default="GBP", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("portfolios", "base_currency")
    # ### end Alembic commands ###
